-- Migration: Add sprint_quali session support
-- Run this in the Supabase SQL editor against your existing database.

-- 1. Add sprint_quali_start column to race_weekends
alter table public.race_weekends
  add column if not exists sprint_quali_start timestamptz;

-- 2. Update CHECK constraints to include 'sprint_quali'
--    Postgres requires dropping and re-adding constraints by name.
--    These are the constraint names generated by Postgres — adjust if yours differ.

-- predictions
alter table public.predictions
  drop constraint if exists predictions_event_type_check;
alter table public.predictions
  add constraint predictions_event_type_check
  check (event_type in ('quali','sprint_quali','sprint','race'));

-- results
alter table public.results
  drop constraint if exists results_event_type_check;
alter table public.results
  add constraint results_event_type_check
  check (event_type in ('quali','sprint_quali','sprint','race'));

-- scores
alter table public.scores
  drop constraint if exists scores_event_type_check;
alter table public.scores
  add constraint scores_event_type_check
  check (event_type in ('quali','sprint_quali','sprint','race'));

-- notification_log
alter table public.notification_log
  drop constraint if exists notification_log_event_type_check;
alter table public.notification_log
  add constraint notification_log_event_type_check
  check (event_type in ('quali','sprint_quali','sprint','race'));

-- results_sync_log
alter table public.results_sync_log
  drop constraint if exists results_sync_log_event_type_check;
alter table public.results_sync_log
  add constraint results_sync_log_event_type_check
  check (event_type in ('quali','sprint_quali','sprint','race'));
